name: Publish Documentation

on:
  push:
    # Pattern matched against branches
    branches:
      - main           # Push events to every new commit pushed to main branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Setup Environments
        run: |
          . work/setup.sh

      - name: Compile Documentations and Deploy
        run: |
          export GOOGLE_ANALYTICS_KEY=$(cat g-analytics-key.txt)
          mkdocs gh-deploy --force
